spring.application.name=clinica

// essas 3 linhas podem mudar de uma maquina pra outra

// essa linha indica onde o sistema deve procurar o banco e qual o nome dele
spring.datasource.url=jdbc:mysql://localhost:3306/clinivet

//esse indica o usuario que foi usado na hora de criar o banco
spring.datasource.username=root

//essa é a senha que você cadastrou no mysql
spring.datasource.password=mysql



spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true